language: python
python: 2.7
sudo: enabled
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - gfortran
install:
- ( cd libcdf && make build && sudo make install )
- ( cd qdipole && ./configure && make build && sudo make install )
- pip install numpy
- pip install SpacePy
- pip install ./eoxmagmod/
script:
- pip list
- mkdir -p ./test && cd ./test
- pip show -f eoxmagmod
- python -c 'import eoxmagmod' && python -m unittest discover -p '[a-z]*.py' -v eoxmagmod
notifications:
  slack:
    secure: cbb7/6s0sglh2q7Lqnlq1I3tF8v2PS3KC+8ppjFFsKGzXWVImTSVU8md06Kkw1Hrf+mXm39x78NQx0o66EzMjZ2GS7SKD3eT3GDRqaF9COrc5zfeshZGF7swu/wtZMMMj0UrTxQnhJx09nwsTWGpCnCyEWOs0tHg+gUzoHqmM+E=
