#
# CDF library conda build metadata
#

{% set version = "3.7.1" %}
{% set file_version = "cdf37_1" %}

package:
  name: "cdf"
  version: {{ version }}

source:
  - url: https://spdf.sci.gsfc.nasa.gov/pub/software/cdf/dist/{{ file_version }}/unix/{{ file_version }}-dist-cdf.tar.gz
    sha256: ef29025b9ac04b02b610803fb6abc84307ae34137742fd6f0c738f9315f0296c

requirements:
  build:
   - ncurses
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}

about:
  home: https://github.com/ESA-VirES/MagneticModel/
