#
# CDF library conda build metadata
#

{% set version = "3.8.0" %}
{% set file_version = "cdf38_0" %}

package:
  name: "cdf"
  version: {{ version }}

source:
  - url: https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/{{ file_version }}/unix/{{ file_version }}-dist-cdf.tar.gz
    sha256: f5d7c2774d017cbb6f70d53a3b12149a52ace4fb089c1ed4ecd352aa6dca27b8

requirements:
  build:
   - ncurses
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}

about:
  home: https://github.com/ESA-VirES/MagneticModel/
