#
# CDF library conda build metadata
#

{% set version = "3.8.0" %}
{% set file_version = "cdf38_0" %}

package:
  name: "cdf"
  version: {{ version }}

source:
  - url: https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/{{ file_version }}/unix/{{ file_version }}-dist-cdf.tar.gz
    sha256: 30a8bc22819791717c0e58ade52cfc1c41c6b5e45a0314718e322874d99fe078

requirements:
  build:
   - ncurses
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}
   - python {{ python }} # added to assure binary compatibility with particular Python/NumPy versions
   - numpy

about:
  home: https://github.com/ESA-VirES/MagneticModel/
